### ISSUE TITLE
运行train_csc.py报错：AttributeError: Can't pickle local object 'get_csc_loader.<locals>._collate_fn'

### ISSUE THREAD

**Issue by xubinxin123** [gitabtion/BertBasedCorrectionModels#7]
依赖包严格按照给出版本号安装
D:\SoftRun\Anaconda3\envs\torch161\python.exe E:/nlpcode/BertBasedCorrectionModels-master/tools/train_csc.py
2021-04-30 13:58:02,496 bert4csc INFO: Namespace(config_file='', opts=[])
2021-04-30 13:58:02,496 bert4csc INFO: Loaded configuration file csc/train_bert4csc.yml
2021-04-30 13:58:02,496 bert4csc INFO: 
MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 1.0 ]
  GPU_IDS: [0]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 16
  WARMUP_EPOCHS: 8
  MAX_EPOCHS: 20
  ACCUMULATE_GRAD_BATCHES: 16

TEST:
  BATCH_SIZE: 16

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/bert4csc"

2021-04-30 13:58:02,496 bert4csc INFO: Running with config:
DATALOADER:
  NUM_WORKERS: 4
DATASETS:
  TEST: datasets/csc/test.json
  TRAIN: datasets/csc/train.json
  VALID: datasets/csc/dev.json
INPUT:
  MAX_LEN: 512
MODE: ['train', 'test']
MODEL:
  BERT_CKPT: bert-base-chinese
  DEVICE: cuda:0
  GPU_IDS: [0]
  HYPER_PARAMS: [1.0]
  NAME: bert4csc
  NUM_CLASSES: 10
  WEIGHTS: 
OUTPUT_DIR: checkpoints/bert4csc
SOLVER:
  ACCUMULATE_GRAD_BATCHES: 16
  BASE_LR: 0.001
  BATCH_SIZE: 16
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 10
  GAMMA: 0.1
  LOG_PERIOD: 100
  MAX_EPOCHS: 20
  MOMENTUM: 0.9
  OPTIMIZER_NAME: AdamW
  STEPS: (30000,)
  WARMUP_EPOCHS: 8
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 1e-05
  WEIGHT_DECAY_BIAS: 0
TASK:
  NAME: csc
TEST:
  BATCH_SIZE: 16
  CKPT_FN: 
Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\utilities\distributed.py:49: UserWarning: Checkpoint directory E:\nlpcode\BertBasedCorrectionModels-master\checkpoints\bert4csc exists and is not empty.
  warnings.warn(*args, **kwargs)
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name | Type            | Params
-----------------------------------------
0 | bert | BertForMaskedLM | 102 M 
-----------------------------------------
102 M     Trainable params
0         Non-trainable params
102 M     Total params
Validation sanity check: 0it [00:00, ?it/s]2021-04-30 13:58:11,384 bert4csc INFO: Valid.
Traceback (most recent call last):
  File "E:/nlpcode/BertBasedCorrectionModels-master/tools/train_csc.py", line 53, in <module>
    main()
  File "E:/nlpcode/BertBasedCorrectionModels-master/tools/train_csc.py", line 49, in main
    train(cfg, model, loaders, ckpt_callback)
  File "E:\nlpcode\BertBasedCorrectionModels-master\tools\bases.py", line 78, in train
    trainer.fit(model, train_loader, valid_loader)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 470, in fit
    results = self.accelerator_backend.train()
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\accelerators\gpu_accelerator.py", line 68, in train
    results = self.train_or_test()
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 492, in train
    self.run_sanity_check(self.get_model())
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 690, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 593, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\SoftRun\Anaconda3\envs\torch161\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_csc_loader.<locals>._collate_fn'

Process finished with exit code 1

**Comment by gitabtion** [comment]
将get_csc_loader的内部函数_collate_fn转移至外部即可。

**Comment by xubinxin123** [comment]
已经解决！（不完美，但是代码可以跑起来）
经过查询，这个报错是python多线程和修饰器直接产生的一个bug。我实在找不到修饰器部分的代码，只能从多线程入手，目标是关闭多线程，直接说解决方法：修改configs/csc/train_bert4csc.yml,增加以下两行（macbert和softmaskedbert方法一样）
DATALOADER:
  NUM_WORKERS: 0

以下为原始文件
MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 1.0 ]
  GPU_IDS: [0]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 8
  WARMUP_EPOCHS: 8
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4


TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/bert4csc"

**Comment by xubinxin123** [comment]
已经解决！（不完美，但是代码可以跑起来）
经过查询，这个报错是python多线程和修饰器直接产生的一个bug。我实在找不到修饰器部分的代码，只能从多线程入手，目标是关闭多线程，直接说解决方法：修改configs/csc/train_bert4csc.yml,增加以下两行（macbert和softmaskedbert方法一样）
DATALOADER:
  NUM_WORKERS: 0

以下为原始文件
MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 1.0 ]
  GPU_IDS: [0]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 8
  WARMUP_EPOCHS: 8
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4


TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/bert4csc"

**Comment by xubinxin123** [comment]
已经解决！（不完美，但是代码可以跑起来）
经过查询，这个报错是python多线程和修饰器直接产生的一个bug。我实在找不到修饰器部分的代码，只能从多线程入手，目标是关闭多线程，直接说解决方法：修改configs/csc/train_bert4csc.yml,增加以下两行（macbert和softmaskedbert方法一样）
DATALOADER:
  NUM_WORKERS: 0

以下为原始文件
MODEL:
  BERT_CKPT: "bert-base-chinese"
  DEVICE: "cuda:0"
  NAME: "bert4csc"
  # [loss_coefficient]
  HYPER_PARAMS: [ 1.0 ]
  GPU_IDS: [0]

DATASETS:
  TRAIN: "datasets/csc/train.json"
  VALID: "datasets/csc/dev.json"
  TEST: "datasets/csc/test.json"

SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.00001
  BATCH_SIZE: 8
  WARMUP_EPOCHS: 8
  MAX_EPOCHS: 10
  ACCUMULATE_GRAD_BATCHES: 4


TEST:
  BATCH_SIZE: 8

TASK:
  NAME: "csc"

OUTPUT_DIR: "checkpoints/bert4csc"
